[template.environment]
  GQL_HOST = "https://stage.naturenutricia.com/graphql"
  NUXT_IMAGE_DOMAINS = "stage.naturenutricia.com,naturenutricia.com"

[build]
  command = "nuxt generate"

[images]
  remote_images = [
    "https://stage.naturenutricia.com/wp-content/uploads/",
    "https://naturenutricia.com/wp-content/uploads/",
    "https://www.naturenutricia.com/wp-content/uploads/"
  ]
